name: Build_QEMU_CI_CD
run-name: ${{ github.actor }} is building QEMU_CI_CD for linux using GitHub Actions 🚀
on:
  release:
    types: [created]
jobs:
  Build_ffmpeg_libraries_for_Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install build deps
        run: |
          sudo sed -Ei 's/^# deb-src /deb-src /' /etc/apt/sources.list
          sudo apt update
          yes | sudo apt build-dep qemu
          yes | sudo apt install git
      - name: configure
        run: |
              git submodule update --init --recursive
              mkdir prefix
              ./configure \
              --prefix=$(pwd)/prefix \
              --static \
              --disable-system \
              --enable-linux-user
      - name: build qemu
        run: |
          make
          make install
      - name: upload QEMU CI CD binaries to release
        run: |
          ID=$(jq --raw-output '.release.id' $GITHUB_EVENT_PATH)
          AUTH_HEADER="Authorization: token ${{ secrets.GITHUB_TOKEN }}"
          CONTENT_LENGTH="Content-Length: $(stat -c%s prefix/qemu-aarch64)"
          CONTENT_TYPE="Content-Type:  application/x-elf"
          UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/$ID/assets?name=qemu-aarch64-static"
          curl -XPOST -H "$AUTH_HEADER" -H "$CONTENT_LENGTH" -H "$CONTENT_TYPE" --upload-file "prefix/qemu-aarch64" "$UPLOAD_URL"
          CONTENT_LENGTH="Content-Length: $(stat -c%s prefix/qemu-arm)"
          CONTENT_TYPE="Content-Type:  application/x-elf"
          UPLOAD_URL="https://uploads.github.com/repos/${{ github.repository }}/releases/$ID/assets?name=qemu-arm-static"
          curl -XPOST -H "$AUTH_HEADER" -H "$CONTENT_LENGTH" -H "$CONTENT_TYPE" --upload-file "prefix/qemu-arm" "$UPLOAD_URL"
      - run: echo "🍏 This job's status is ${{ job.status }}."
